import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useTheme } from "next-themes" 
import { useEffect, useState } from 'react'

const Home: NextPage = () => {
  const { theme, setTheme } = useTheme();
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  const switchTheme = () => {
    if (isMounted) {
      setTheme(theme === "light" ? "dark" : "light");
    }
};
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-red-500">
        <button onClick={switchTheme}>Change theme</button>
      </main>

    </div>
  )
}

export default Home
